### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by csandor** [mixu/electroshot#2]
I tried this:
electroshot google.com 1366x768

Got this:
![image](https://cloud.githubusercontent.com/assets/1776830/15576073/58ef4a8e-2356-11e6-83fd-9f8947bcf628.png)

Windows 10. Node 4.4.5 (was the same on Node 4.3.x

**Comment by mixu** [comment]
finally fixed in `v1.2.0` which adds full Windows compatibility (and updates Electron to a 2017 release)
