### ISSUE TITLE
CSS usage?

### ISSUE THREAD

**Issue by JacksonGariety** [mixu/electroshot#3]
this command
`electroshot yahoo.com 1000x1000 --css="body { display: none !important; }"`

seems not to work.

neither does this one:

`electroshot yahoo.com 1000x1000 --js="document.querySelector('html').style.display = 'none'"`

Am I missing something?

**Comment by vogievetsky** [comment]
I am seeing the same issue

**Comment by mixu** [comment]
fixed in `v1.3.0`
