### ISSUE TITLE
custom timeout

### ISSUE THREAD

**Issue by thr3a** [mixu/electroshot#8]
I could not find the option to time out the electroshot.

But README has a description of custom timeout.

Is there an option to time out?

I read [chrome-command-line-switches](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md) , but I could not find it.

**Comment by mixu** [comment]
https://github.com/mixu/electroshot#page-rendering-delay-selector-zoom-factor

> To introduce a delay to the page capture, specify --delay <ms>. The default value is 0, which simply waits until two requestAnimationFrame calls have passed. This is usually enough time to capture something reasonable.
> 
> You can set multiple --delays to capture the page(s) at multiple points in time. Combined with --emulate-network, this can produce a full timeline of loading a specific page under slow network access.
